apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safework

resources:
  # Cloudflare Tunnel 리소스
  - tunnel-secret.yaml
  - cloudflared-deployment.yaml
  - tunnel-config.yaml
  
  # SafeWork 서비스를 ClusterIP로 변경
  - safework-service-clusterip.yaml

# 기존 NodePort 서비스를 ClusterIP로 대체
patches:
  - target:
      kind: Service
      name: safework
    path: safework-service-clusterip.yaml