apiVersion: v1
kind: Service
metadata:
  name: safework
  namespace: safework
  labels:
    app: safework
spec:
  type: ClusterIP  # NodePort에서 ClusterIP로 변경 - 외부 직접 접근 차단
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: safework