apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: safework
type: Opaque
data:
  token: ZXlKaElqb2lZVGhrT1dNMk4yWTFPRFpoWTJSa01UVmxaV0pqWXpZMVkyRXpZV0UxWW1JaUxDSjBJam9pT0dWaE56ZzVNRFl0TVdFd05TMDBOR1ppTFdFeFltSXRaVFV4TWpFM01tTmlOV0ZpSWl3aWN5STZJbGw2UlhsWlZFVXdXV3BSZEUxdFZYbE5VekF3V21wUk1FeFhTVFZhUjBWMFdrZE5NMDlVWTNwT1YxRXhUMVJHYlNKOQ==
