apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: safework
data:
  config.yaml: |
    # 이 설정은 참고용입니다. 
    # TUNNEL_TOKEN을 사용하는 원격 관리 터널의 경우,
    # 모든 라우팅 설정은 Cloudflare Zero Trust 대시보드에서 관리됩니다.
    #
    # Cloudflare Zero Trust 대시보드에서 다음과 같이 설정하세요:
    # 
    # Public Hostname 설정:
    # - Subdomain: safework (또는 원하는 서브도메인)
    # - Domain: jclee.me (또는 귀하의 도메인)
    # - Path: /*
    # - Service: http://safework.safework.svc.cluster.local:3001
    #
    # 추가 보안 설정 (선택사항):
    # - Access Policy 설정으로 특정 이메일/IP만 허용
    # - Web Application Firewall (WAF) 규칙 적용
    # - Rate Limiting 설정
    
    # 로컬 설정 파일을 사용하는 경우 (참고용):
    tunnel: YOUR_TUNNEL_ID
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: safework.jclee.me
        service: http://safework.safework.svc.cluster.local:3001
      - service: http_status:404