# Default values for safework
replicaCount: 1

image:
  repository: registry.jclee.me/safework
  pullPolicy: IfNotPresent
  tag: "prod-20250122-c6a116d"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3001
  nodePort: 32301

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

config:
  environment: production
  appName: "SafeWork Pro"
  logLevel: INFO