version: '3.8'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - '1234:5000'
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      # Disable authentication
      REGISTRY_AUTH: 'none'
      # Allow all hosts
      REGISTRY_HTTP_HOST: 'http://0.0.0.0:5000'
    volumes:
      - /volume1/app/registry/data:/var/lib/registry
    networks:
      - registry-network

networks:
  registry-network:
    driver: bridge