# Staging environment overrides
replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 512Mi

env:
  - name: ENVIRONMENT
    value: "staging"
  - name: LOG_LEVEL
    value: "DEBUG"