apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safework.fullname" . }}-config
  labels:
    {{- include "safework.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment }}
  APP_NAME: {{ .Values.config.appName }}
  LOG_LEVEL: {{ .Values.config.logLevel }}
  DATABASE_HOST: {{ .Values.database.host }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name }}
  DATABASE_USER: {{ .Values.database.user }}
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_DB: {{ .Values.redis.db | quote }}