apiVersion: v1
kind: Secret
metadata:
  name: safework-secrets
  labels:
    {{- include "safework.labels" . | nindent 4 }}
type: Opaque
data:
  # Database password (base64 encoded)
  database-password: {{ .Values.database.password | default "YWRtaW4xMjM0NSE=" | b64enc }}
  # JWT secret key (base64 encoded)
  jwt-secret: {{ .Values.security.jwtSecret | default "c2FmZXdvcmstand0LXNlY3JldC1rZXktZm9yLXByb2R1Y3Rpb24tMjAyNQ==" | b64enc }}
  # Application secret key (base64 encoded)
  secret-key: {{ .Values.security.secretKey | default "c2FmZXdvcmstYXBwbGljYXRpb24tc2VjcmV0LWtleS0yMDI1" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    {{- include "safework.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"registry.jclee.me\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" (.Values.registry.username | default "admin") (.Values.registry.password | default "bingogo1") (.Values.registry.auth | default "YWRtaW46YmluZ29nbzE=") | b64enc }}