apiVersion: v1
kind: Secret
metadata:
  name: helm-charts-jclee-me
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: https://charts.jclee.me
  username: admin
  password: bingogo1