apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    chart: safework
    targetRevision: ">=1.0.0"
    helm:
      releaseName: safework
      values: |
        replicaCount: 1
        image:
          tag: "latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
