version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    environment:
      # Core Configuration
      - WATCHTOWER_POLL_INTERVAL=30              # Check every 30 seconds
      - WATCHTOWER_CLEANUP=true                  # Remove old images
      - WATCHTOWER_INCLUDE_STOPPED=false         # Don't update stopped containers
      - WATCHTOWER_INCLUDE_RESTARTING=true       # Update restarting containers
      - WATCHTOWER_LABEL_ENABLE=true             # Only update labeled containers
      - WATCHTOWER_ROLLING_RESTART=true          # Zero-downtime updates
      - WATCHTOWER_NO_PULL=false                 # Pull images from registry
      - WATCHTOWER_MONITOR_ONLY=false            # Actually perform updates
      - WATCHTOWER_TIMEOUT=300                   # 5 minute timeout per update
      
      # Authentication
      - DOCKER_CONFIG=/config.json               # Use mounted config for registry auth
      
      # Notifications (optional)
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-log}
      - WATCHTOWER_NOTIFICATION_LEVEL=info
      
      # Timezone
      - TZ=Asia/Seoul
      
      # HTTP API for manual triggers (optional)
      - WATCHTOWER_HTTP_API_UPDATE=${WATCHTOWER_API_ENABLED:-false}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN:-your-secure-token-here}
    command: --interval 30 --label-enable --cleanup --rolling-restart
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Don't auto-update watchtower itself
    networks:
      - health-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "8080:8080"  # API endpoint (only if WATCHTOWER_HTTP_API_UPDATE=true)

  health-app:
    image: registry.jclee.me/health-management-system:latest
    container_name: health-management-system
    restart: unless-stopped
    ports:
      - "3001:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/health_management
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=your-super-secret-jwt-key-here-32-chars-long
      - DEBUG=false
      - LOG_LEVEL=INFO
      - TZ=Asia/Seoul
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./dist:/app/dist
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.stop-signal=SIGTERM"
      - "com.centurylinklabs.watchtower.timeout=30s"
    depends_on:
      - postgres
      - redis
    networks:
      - health-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15
    container_name: health-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=health_management
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - health-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d health_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: health-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - health-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  health-network:
    driver: bridge