version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: safework-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: safework123
      POSTGRES_DB: health_management
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d health_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: safework-redis
    restart: unless-stopped
    command: redis-server --bind 0.0.0.0 --protected-mode no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: registry.jclee.me/safework:latest
    container_name: safework-app
    restart: unless-stopped
    ports:
      - "3001:8000"
    environment:
      DATABASE_URL: postgresql://admin:safework123@postgres:5432/health_management
      REDIS_URL: redis://redis:6379/0
      JWT_SECRET: safework-secret-key-2024
      DEBUG: "false"
      LOG_LEVEL: INFO
      TZ: Asia/Seoul
      BUILD_TIME: "${BUILD_TIME:-2025-06-26 12:00:00 KST}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres_data:

networks:
  default:
    name: safework-simple-network