version: '3.8'

services:
  safework-pro:
    build:
      context: .
      dockerfile: Dockerfile.all-in-one
      args:
        BUILD_TIME: "${BUILD_TIME:-$(date +'%Y-%m-%d %H:%M:%S KST')}"
    image: registry.jclee.me/safework-pro-aio:latest
    container_name: safework-pro-all-in-one
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # PostgreSQL settings
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-health_management}
      
      # Application settings
      DATABASE_URL: ${DATABASE_URL:-postgresql://admin:password@localhost:5432/health_management}
      REDIS_URL: ${REDIS_URL:-redis://localhost:6379/0}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-here}
      DEBUG: ${DEBUG:-false}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      TZ: Asia/Seoul
    volumes:
      # Named volumes for data persistence
      - postgres_data:/var/lib/postgresql/data
      - app_uploads:/app/uploads
      - app_logs:/app/logs
      - redis_data:/var/lib/redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

# Named volumes
volumes:
  postgres_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local
  redis_data:
    driver: local