version: '3.8'

services:
  # SafeWork Pro - Production All-in-One
  safework:
    image: registry.jclee.me/safework:latest
    container_name: safework-prod
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      # 데이터베이스 설정
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: safework123
      POSTGRES_DB: health_management
      DATABASE_URL: postgresql://admin:safework123@localhost:5432/health_management
      
      # Redis 설정
      REDIS_URL: redis://localhost:6379/0
      
      # 애플리케이션 설정
      JWT_SECRET: safework-pro-secret-key-2024-production
      DEBUG: "false"
      LOG_LEVEL: INFO
      TZ: Asia/Seoul
      PORT: 3001
      ENVIRONMENT: production
      
      # 빌드 시간
      BUILD_TIME: "${BUILD_TIME:-2025-06-26 01:30:00 KST}"
    
    volumes:
      # 데이터 볼륨 (Docker 관리)
      - safework_data:/var/lib/postgresql/data
      - safework_redis:/var/lib/redis
      - safework_uploads:/app/uploads
      - safework_logs:/app/logs
    
    labels:
      # Watchtower 자동 업데이트
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
      
      # 메타데이터
      - "org.opencontainers.image.title=SafeWork Pro"
      - "org.opencontainers.image.description=건설업 보건관리 시스템 (운영환경)"
      - "org.opencontainers.image.version=1.0.0"
      - "org.opencontainers.image.vendor=SafeWork Pro Team"
      - "org.opencontainers.image.url=https://safework.jclee.me"
      - "org.opencontainers.image.source=https://github.com/JCLEE94/safework"
      - "traefik.enable=true"
      - "traefik.http.routers.safework.rule=Host(`safework.jclee.me`)"
      - "traefik.http.routers.safework.tls=true"
      - "traefik.http.routers.safework.tls.certresolver=letsencrypt"
      - "traefik.http.services.safework.loadbalancer.server.port=3001"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    
    # 보안 설정
    security_opt:
      - no-new-privileges:true
    
    # 리소스 제한
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    # 임시 파일시스템
    tmpfs:
      - /tmp:size=100M
      - /var/tmp:size=50M

# 볼륨 정의
volumes:
  safework_data:
    driver: local
    labels:
      - "description=SafeWork Pro PostgreSQL 데이터"
  safework_redis:
    driver: local
    labels:
      - "description=SafeWork Pro Redis 데이터"
  safework_uploads:
    driver: local
    labels:
      - "description=SafeWork Pro 업로드 파일"
  safework_logs:
    driver: local
    labels:
      - "description=SafeWork Pro 로그 파일"

# 네트워크 정의
networks:
  default:
    name: safework-production
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-safework-prod
    labels:
      - "description=SafeWork Pro 운영 네트워크"