version: '3.8'

services:
  health-app:
    image: registry.jclee.me/health:latest
    container_name: health-app-1
    restart: unless-stopped
    ports:
      - "3001:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      DEBUG: "false"
      LOG_LEVEL: INFO
      TZ: Asia/Seoul
    volumes:
      - /volume1/app/health/uploads:/app/uploads
      - /volume1/app/health/logs:/app/logs
    networks:
      - health-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  health-network:
    external: true