version: '3.8'

services:
  # SafeWork Pro - All-in-One 컨테이너 (PostgreSQL + Redis + FastAPI + React)
  safework:
    image: registry.jclee.me/safework:latest
    container_name: safework
    restart: unless-stopped
    ports:
      - "3001:8000"
    environment:
      # 환경 구분
      ENVIRONMENT: production
      DEBUG: "false"
      
      # 데이터베이스 설정 (All-in-One 내장)
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-health_management}
      DATABASE_URL: ${DATABASE_URL:-postgresql://admin:password@localhost:5432/health_management}
      
      # Redis 설정 (All-in-One 내장)
      REDIS_URL: redis://localhost:6379/0
      
      # 애플리케이션 설정
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
      LOG_LEVEL: INFO
      TZ: Asia/Seoul
      HOST: 0.0.0.0
      PORT: 8000
      
      # 성능 설정
      WORKERS: 4
      WORKER_CLASS: uvicorn.workers.UvicornWorker
      
      # 보안 설정
      CORS_ORIGINS: "*"
      TRUSTED_HOSTS: "*"
      
      # 파일 업로드
      MAX_UPLOAD_SIZE: 100MB
      
      # 메타데이터
      BUILD_TIME: "2025-06-30 07:00:00 KST"
      GIT_COMMIT: latest
      VERSION: 1.0.0
    
    volumes:
      # 애플리케이션 데이터 볼륨 (상대경로 방식)
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./instance:/app/instance
    
    labels:
      # Watchtower 자동 업데이트
      - "com.centurylinklabs.watchtower.enable=true"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    
    # 보안 설정 (운영환경만)
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    
    # 임시 파일시스템 최적화
    tmpfs:
      - /tmp:size=500M,mode=1777
      - /var/tmp:size=200M,mode=1777

# 네트워크 정의
networks:
  default:
    name: safework-network