apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-service-tokens
  namespace: safework
  labels:
    app: safework
    component: authentication
    security: service-tokens
type: Opaque
stringData:
  # Cloudflare Team Domain
  CLOUDFLARE_TEAM_DOMAIN: "your-team-domain"
  
  # Service Token Configuration
  ENABLE_SERVICE_TOKEN_VALIDATION: "true"
  ENABLE_SERVICE_TOKEN_RATE_LIMITING: "true"
  ENABLE_SERVICE_TOKEN_AUDIT: "true"
  SERVICE_TOKEN_CACHE_TTL: "300"
  SERVICE_TOKEN_RATE_LIMIT_WINDOW: "3600"
  
  # API Service Token
  CF_SERVICE_TOKEN_API_CLIENT_ID: "api-client-id-placeholder"
  CF_SERVICE_TOKEN_API_CLIENT_SECRET: "api-client-secret-placeholder"
  SERVICE_TOKEN_API_RATE_LIMIT: "1000"
  
  # Registry Service Token
  CF_SERVICE_TOKEN_REGISTRY_CLIENT_ID: "registry-client-id-placeholder"
  CF_SERVICE_TOKEN_REGISTRY_CLIENT_SECRET: "registry-client-secret-placeholder"
  SERVICE_TOKEN_REGISTRY_RATE_LIMIT: "500"
  
  # CI/CD Service Token
  CF_SERVICE_TOKEN_CICD_CLIENT_ID: "cicd-client-id-placeholder"
  CF_SERVICE_TOKEN_CICD_CLIENT_SECRET: "cicd-client-secret-placeholder"
  SERVICE_TOKEN_CICD_RATE_LIMIT: "100"
  
  # Monitoring Service Token
  CF_SERVICE_TOKEN_MONITORING_CLIENT_ID: "monitoring-client-id-placeholder"
  CF_SERVICE_TOKEN_MONITORING_CLIENT_SECRET: "monitoring-client-secret-placeholder"
  SERVICE_TOKEN_MONITORING_RATE_LIMIT: "2000"
---
# Note: This is a template file
# In production, replace placeholders with actual service token values
# Create service tokens in Cloudflare Zero Trust Dashboard:
# https://one.dash.cloudflare.com/
# 
# Steps:
# 1. Go to Access → Service Tokens
# 2. Create tokens for each service (api, registry, cicd, monitoring)
# 3. Copy client ID and client secret
# 4. Update this file with actual values
# 5. Apply to cluster: kubectl apply -f k8s/secrets/cloudflare-service-tokens.yaml
#
# Security reminder:
# - Never commit actual secrets to version control
# - Use sealed-secrets or external-secrets for production
# - Rotate tokens regularly (recommended: every 3-6 months)