version: '3.8'

# SafeWork Pro - 운영 서버용 Docker Compose (All-in-One 최적화)
# registry.jclee.me 기반 자동 배포 + Watchtower 통합

services:
  # SafeWork Pro 메인 애플리케이션 (All-in-One)
  safework:
    image: registry.jclee.me/safework:latest
    container_name: safework
    restart: unless-stopped
    ports:
      - "3001:8000"
    environment:
      # 핵심 설정
      ENVIRONMENT: production
      DEBUG: "false"
      
      # 데이터베이스 설정 (All-in-One 내장)
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: safework123
      POSTGRES_DB: health_management
      DATABASE_URL: postgresql://admin:safework123@localhost:5432/health_management
      
      # Redis 설정 (All-in-One 내장)
      REDIS_URL: redis://localhost:6379/0
      
      # 보안 설정
      JWT_SECRET: ${JWT_SECRET:-safework-pro-jwt-secret-2025-${BUILD_TIME:-production}}
      SECRET_KEY: ${SECRET_KEY:-safework-pro-app-secret-2025-${BUILD_TIME:-production}}
      
      # 서버 설정
      HOST: 0.0.0.0
      PORT: 8000
      WORKERS: 4
      WORKER_CLASS: uvicorn.workers.UvicornWorker
      
      # 시스템 설정
      TZ: Asia/Seoul
      LANG: ko_KR.UTF-8
      LC_ALL: ko_KR.UTF-8
      
      # 로깅 설정
      LOG_LEVEL: INFO
      LOG_FORMAT: json
      
      # CORS 및 보안
      CORS_ORIGINS: "https://192.168.50.215:3001,http://192.168.50.215:3001,https://safework.jclee.me"
      TRUSTED_HOSTS: "192.168.50.215,safework.jclee.me,localhost"
      
      # 파일 업로드
      MAX_UPLOAD_SIZE: 100MB
      UPLOAD_PATH: /app/uploads
      
      # 성능 최적화
      CACHE_TTL: 3600
      SESSION_TIMEOUT: 86400
      
      # 백업 설정
      BACKUP_ENABLED: "true"
      BACKUP_SCHEDULE: "0 2 * * *"
      BACKUP_RETENTION_DAYS: 30
      
      # 모니터링
      ENABLE_METRICS: "true"
      HEALTH_CHECK_INTERVAL: 30
      
      # 빌드 정보
      BUILD_TIME: "${BUILD_TIME:-$(date '+%Y-%m-%d %H:%M:%S KST')}"
      GIT_COMMIT: "${GITHUB_SHA:-unknown}"
      VERSION: "${VERSION:-1.0.0}"
    
    volumes:
      - safework_uploads:/app/uploads
      - safework_logs:/app/logs
    
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s  # All-in-One은 시작 시간이 더 오래 걸림
    
    # 보안 설정
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    
    # 리소스 제한 제거 (호스트 자원 전체 활용)
    
    # 임시 파일시스템 (성능 최적화)
    tmpfs:
      - /tmp:size=500M,mode=1777
      - /var/tmp:size=200M,mode=1777
      - /dev/shm:size=256M

# 볼륨 정의
volumes:
  safework_uploads:
  safework_logs:

# 네트워크 정의 (기본 설정 사용)
networks:
  default:
    name: safework-production