version: '3.8'

services:
  app:
    image: registry.jclee.me/safework:latest
    container_name: safework
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://admin:safework123@localhost:5432/health_management
      REDIS_URL: redis://localhost:6379/0
      JWT_SECRET: safework-secret-key-2024
      DEBUG: "false"
      LOG_LEVEL: INFO
      TZ: Asia/Seoul
      DISABLE_AUTH: "true"
      BUILD_TIME: "${BUILD_TIME:-2025-06-26 12:00:00 KST}"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - postgres_data:/var/lib/postgresql/data
      - redis_data:/var/lib/redis
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: safework-single-network