apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: registry.jclee.me/safework
    newTag: prod-latest

configMapGenerator:
  - name: safework-config
    behavior: merge
    literals:
      - environment=production
      - log_level=warning
      - cors_origins=https://safework.jclee.me
      - database_host=postgres-prod
      - redis_host=redis-prod

secretGenerator:
  - name: safework-secret
    envs:
      - .env.secret

replicas:
  - name: safework
    count: 3