apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safework-ingress
  namespace: safework
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: safework.jclee.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: safework
            port:
              number: 3001