apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safework

resources:
  # 네임스페이스
  - namespace.yaml
  
  # 시크릿
  - secrets.yaml
  - regcred.yaml
  
  # 데이터베이스
  - postgres.yaml
  - redis.yaml
  
  # 애플리케이션
  - deployment.yaml
  - service.yaml
  
  # Cloudflare Tunnel (옵션: Cloudflare Tunnel 사용 시 활성화)
  # - ../cloudflare/

# ArgoCD에서 자동으로 이미지를 업데이트하기 위한 설정
images:
  - name: registry.jclee.me/safework
    newTag: prod-2025.07.08.57-b00231b