apiVersion: v1
kind: ResourceQuota
metadata:
  name: safework-quota
  namespace: safework
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: "4Gi"
    limits.cpu: "4000m" 
    limits.memory: "8Gi"
    pods: "10"
    persistentvolumeclaims: "5"