---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: safework-quota
  namespace: safework
  labels:
    app: safework
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: 4Gi
    limits.cpu: "4000m"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: safework-limits
  namespace: safework
  labels:
    app: safework
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    max:
      cpu: 2000m
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Container