apiVersion: v1
kind: Service
metadata:
  name: safework
  namespace: safework
  labels:
    app: safework
spec:
  type: LoadBalancer
  ports:
  - port: 33301
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: safework