apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safework

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: registry.jclee.me/safework-frontend
  newTag: latest

labels:
- pairs:
    app.kubernetes.io/name: safework
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: safework