{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "safework.fullname" . }}-quota
  labels:
    {{- include "safework.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.limits | nindent 4 }}
{{- end }}
---
{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "safework.fullname" . }}-limits
  labels:
    {{- include "safework.labels" . | nindent 4 }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}