apiVersion: v1
kind: Secret
metadata:
  name: safework-secrets
  labels:
    {{- include "safework.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.jwtSecret | default "your-secret-key-here" | b64enc }}
---
{{- if .Values.dockerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    {{- include "safework.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerRegistry.server .Values.dockerRegistry.username .Values.dockerRegistry.password (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc) | b64enc }}
{{- end }}