apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/safework
    path: charts/safework
    targetRevision: HEAD
    helm:
      values: |
        service:
          targetPort: 8000
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true