apiVersion: apps/v1
kind: Deployment
metadata:
  name: safework
  namespace: safework
  annotations:
    # ArgoCD Image Updater 설정 강화
    argocd-image-updater.argoproj.io/image-list: safework=registry.jclee.me/safework
    argocd-image-updater.argoproj.io/safework.update-strategy: latest
    argocd-image-updater.argoproj.io/safework.allow-tags: regexp:^prod-[0-9]{8}-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/safework.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safework
  template:
    metadata:
      labels:
        app: safework
        version: "prod-latest"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: safework
        image: registry.jclee.me/safework:hotfix-final
        ports:
        - containerPort: 3001
          name: http
        envFrom:
        - secretRef:
            name: safework-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: safework
  namespace: safework
spec:
  selector:
    app: safework
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP