apiVersion: apps/v1
kind: Deployment
metadata:
  name: safework
  namespace: safework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safework
  template:
    metadata:
      labels:
        app: safework
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: safework
        image: registry.jclee.me/safework@sha256:f081d76964aaa6a967bbe3e75e65b9717da2fb6c14a7fd11f865c95cc7a6fb5b
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:password@localhost:5432/health_management"
        - name: REDIS_URL
          value: "redis://localhost:6379/0"
        - name: JWT_SECRET
          value: "your-secret-key-here"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: safework
  namespace: safework
spec:
  selector:
    app: safework
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP