apiVersion: apps/v1
kind: Deployment
metadata:
  name: safework
  namespace: safework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safework
  template:
    metadata:
      labels:
        app: safework
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: safework
        image: registry.jclee.me/safework@sha256:71f929af7d9e072686b2209b0124de49f3510bbccb76d4c249cbcccee3989ae0
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:password@localhost:5432/health_management"
        - name: REDIS_URL
          value: "redis://localhost:6379/0"
        - name: JWT_SECRET
          value: "your-secret-key-here"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: safework
  namespace: safework
spec:
  selector:
    app: safework
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP