"""add worker feedback table

Revision ID: add_worker_feedback_20250121
Revises: 
Create Date: 2025-01-21

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_worker_feedback_20250121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='피드백 내용'),
    sa.Column('photo_url', sa.Text(), comment='첨부 사진 URL'),
    sa.Column('created_by', sa.String(length=50), comment='작성자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_feedbacks_worker_id'), 'worker_feedbacks', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_feedbacks_worker_id'), table_name='worker_feedbacks')
    op.drop_table('worker_feedbacks')
    # ### end Alembic commands ###