apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: registry.jclee.me/safework
    newTag: dev-latest

configMapGenerator:
  - name: safework-config
    behavior: merge
    literals:
      - environment=development
      - log_level=debug
      - cors_origins=http://localhost:3000,http://localhost:5173
      - database_host=postgres-dev
      - redis_host=redis-dev

secretGenerator:
  - name: safework-secret
    envs:
      - .env.secret

replicas:
  - name: safework
    count: 1