apiVersion: v2
name: safework
description: SafeWork Pro - 건설업 보건관리 시스템
type: application
version: 0.1.0-53  # Redis 포트 설정 오류 수정 - REDIS_HOST/PORT 환경변수 분리
appVersion: "0.1.0-53"  # Redis 포트 설정 오류 수정 - REDIS_HOST/PORT 환경변수 분리
keywords:
  - safework
  - health-management
  - construction
home: https://github.com/JCLEE94/safework
sources:
  - https://github.com/JCLEE94/safework
maintainers:
  - name: SafeWork Team
    email: admin@jclee.me
