replicaCount: 1

image:
  repository: registry.jclee.me/safework
  pullPolicy: Always
  tag: "latest"  # 기본값, ArgoCD Image Updater가 자동으로 업데이트

imagePullSecrets:
  - name: harbor-registry

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8000
  nodePort: 32301

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: safework.jclee.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: safework-tls
      hosts:
        - safework.jclee.me

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

env:
  - name: ENVIRONMENT
    value: "production"
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "8000"
  - name: DATABASE_URL
    value: "postgresql://admin:safework123@postgres:5432/health_management"
  - name: REDIS_URL
    value: "redis://redis:6379/0"
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: safework-secrets
        key: jwt-secret
  - name: LOG_LEVEL
    value: "INFO"
  - name: TZ
    value: "Asia/Seoul"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# PostgreSQL 설정 (내장)
postgresql:
  enabled: false  # SafeWork는 all-in-one 컨테이너 사용
  name: safework-postgres
  image:
    repository: postgres
  auth:
    database: health_management
    username: admin
    password: password
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: false
    size: 5Gi
  
# Redis 설정 (내장)
redis:
  enabled: false  # SafeWork는 all-in-one 컨테이너 사용
  name: safework-redis
  image:
    repository: redis
    tag: "latest"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  persistence:
    enabled: false
    size: 1Gi

# Docker Registry 설정
dockerRegistry:
  enabled: false  # imagePullSecrets에서 직접 설정

# Resource Quota 설정
resourceQuota:
  enabled: false
  
# Network Policy 설정  
networkPolicy:
  enabled: false
  
# Limit Range 설정
limitRange:
  enabled: false

probes:
  liveness:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
