replicaCount: 1

image:
  repository: registry.jclee.me/safework
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

service:
  type: NodePort
  port: 3001
  targetPort: 3001
  nodePort: 32301

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  DATABASE_URL: "postgresql://admin:password@postgres:5432/health_management"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JWT_SECRET: "prod-jwt-secret-key"
  ENVIRONMENT: "production"
  TZ: "Asia/Seoul"