replicaCount: 1

image:
  repository: registry.jclee.me/safework
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3001
  nodePort: 32301

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: safework.jclee.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: safework-tls
      hosts:
        - safework.jclee.me

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

env:
  - name: ENVIRONMENT
    value: "production"
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "3001"
  - name: DATABASE_URL
    value: "postgresql://admin:password@localhost:5432/health_management"
  - name: REDIS_URL
    value: "redis://localhost:6379/0"
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: safework-secrets
        key: jwt-secret
  - name: LOG_LEVEL
    value: "INFO"
  - name: TZ
    value: "Asia/Seoul"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

probes:
  liveness:
    httpGet:
      path: /health
      port: 3001
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    httpGet:
      path: /health
      port: 3001
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
