replicaCount: 1

image:
  repository: registry.jclee.me/safework
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: harbor-registry

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  NODE_ENV: production
  PORT: "8000"