apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safework.fullname" . }}-config
  labels:
    {{- include "safework.labels" . | nindent 4 }}
data:
  app-config.yaml: |
    environment: production
    log_level: INFO
