apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safework.fullname" . }}-config
  labels:
    {{- include "safework.labels" . | nindent 4 }}
data:
  app-config.yaml: |
    environment: {{ .Values.env | map (dict "name" "ENVIRONMENT") | first | default (dict "value" "production") | pluck "value" | first }}
    log_level: {{ .Values.env | map (dict "name" "LOG_LEVEL") | first | default (dict "value" "INFO") | pluck "value" | first }}
