apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"registry.jclee.me\":{\"username\":\"admin\",\"password\":\"bingogo1\",\"auth\":\"%s\"}}}" (printf "admin:bingogo1" | b64enc) | b64enc }}