apiVersion: v1
kind: Secret
metadata:
  name: safework-secrets
  labels:
    {{- include "safework.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.jwtSecret | default "your-secret-key-here" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    {{- include "safework.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get "secrets/regcred.json" | b64enc }}