# SafeWork Pro - 프로젝트 설정
project:
  name: "SafeWork Pro"
  description: "건설업 보건관리 시스템"
  version: "1.0.0"
  
  # Repository settings
  repository:
    name: "health"
    owner: "JCLEE94"
    url: "https://github.com/JCLEE94/health"
    
  # Docker Registry settings  
  registry:
    url: "registry.jclee.me"
    namespace: "health"
    
  # Deployment settings
  deployment:
    production:
      host: "safework.jclee.me"
      port: 443
      user: "kubernetes"
      path: "/deployments/safework"
      compose_file: "k8s-deployment.yaml"
      service_name: "safework"
      
  # Port configuration
  ports:
    frontend: 3001
    backend: 8000
    postgres: 5432
    redis: 6379
    
  # Test ports (to avoid conflicts)
  test_ports:
    postgres: 15432
    redis: 16379