apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safework

resources:
  # Cloudflare Tunnel 리소스만 포함 (Service 제외)
  - ../cloudflare/tunnel-secret.yaml
  - ../cloudflare/cloudflared-deployment.yaml
  - ../cloudflare/tunnel-config.yaml