apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/safework.git
    targetRevision: main
    path: k8s/safework
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    syncOptions:
      - CreateNamespace=true