apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
  labels:
    app: safework
    environment: production
    cloudflare: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/safework.git
    targetRevision: main
    path: k8s/safework-with-cloudflare  # Cloudflare Tunnel이 포함된 경로
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: v1
      kind: Secret
      name: cloudflare-tunnel-token
      jsonPointers:
        - /data/token  # CI/CD에서 동적으로 생성되므로 차이 무시
  info:
    - name: 'Project'
      value: 'SafeWork Pro - 건설업 보건관리 시스템'
    - name: 'Repository'
      value: 'https://github.com/JCLEE94/safework'
    - name: 'Registry'
      value: 'registry.jclee.me/safework'
    - name: 'Production'
      value: 'https://safework.jclee.me'
    - name: 'Cloudflare Tunnel'
      value: 'Enabled'