apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
  labels:
    app: safework
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: safework=registry.jclee.me/safework:latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/safework.git
    targetRevision: main
    path: k8s/safework
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  info:
    - name: 'Project URL'
      value: 'https://github.com/JCLEE94/safework'
    - name: 'Registry'
      value: 'registry.jclee.me/safework'
    - name: 'Production URL'
      value: 'https://safework.jclee.me'