apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework-helm
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: safework=registry.jclee.me/safework:latest
    argocd-image-updater.argoproj.io/safework.allow-tags: regexp:^prod-[0-9]{8}-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/safework.update-strategy: latest
    argocd-image-updater.argoproj.io/safework.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/safework.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    targetRevision: 0.1.2
    chart: safework
    helm:
      releaseName: safework
      values: |
        image:
          repository: registry.jclee.me/safework
          tag: prod-20250715-1861554
        
        service:
          nodePort: 32301
        
        jwtSecret: "production-jwt-secret-key"
        
        createNamespace: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m