apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
  labels:
    app: safework
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: safework=registry.jclee.me/safework:latest
    argocd-image-updater.argoproj.io/safework.update-strategy: latest
    argocd-image-updater.argoproj.io/safework.allow-tags: "regexp:^prod-[0-9]{8}-[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/safework.git
    targetRevision: main
    path: k8s/safework
    # directory:
    #   recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  info:
    - name: 'Project'
      value: 'SafeWork Pro - 건설업 보건관리 시스템'
    - name: 'Repository'
      value: 'https://github.com/JCLEE94/safework'
    - name: 'Registry'
      value: 'registry.jclee.me/safework'
    - name: 'Production'
      value: 'https://safework.jclee.me'