apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework-helm
  namespace: argocd
  labels:
    app: safework
    environment: production
    deployment-method: helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: safework-project
  source:
    repoURL: https://charts.jclee.me
    targetRevision: "*"  # 최신 버전 사용
    chart: safework
    helm:
      releaseName: safework
      values: |
        image:
          repository: registry.jclee.me/safework
          tag: latest
          pullPolicy: Always
        
        service:
          type: NodePort
          port: 3001
          nodePort: 32301
        
        ingress:
          enabled: false
          className: nginx
          hosts:
            - host: safework.jclee.me
              paths:
                - path: /
                  pathType: Prefix
        
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
        
        postgresql:
          enabled: true
          auth:
            username: admin
            password: password
            database: health_management
          persistence:
            enabled: true
            size: 10Gi
        
        redis:
          enabled: true
          auth:
            enabled: false
          master:
            persistence:
              enabled: true
              size: 1Gi
        
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "3001"
          - name: DATABASE_HOST
            value: "postgres"
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  info:
    - name: 'Project'
      value: 'SafeWork Pro - 건설업 보건관리 시스템'
    - name: 'Chart Repository'
      value: 'https://charts.jclee.me'
    - name: 'Registry'
      value: 'registry.jclee.me/safework'
    - name: 'Production'
      value: 'https://safework.jclee.me'
    - name: 'Deployment Method'
      value: 'Helm Chart'