apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JCLEE94/safework.git
    targetRevision: main
    path: k8s/safework
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # 일단 false로 설정
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m