apiVersion: v1
kind: Secret
metadata:
  name: chartmuseum-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: https://charts.jclee.me
  name: chartmuseum
  username: admin
  password: bingogo1
  enableOCI: "false"