apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  # Git credentials for write-back
  # Replace with actual GitHub token
  git-creds: |
    https://github-token:${GITHUB_TOKEN}@github.com
  
  # Registry credentials (not needed for public registry)
  # Kept for future use if needed
  registry-creds: |
    registries:
    - name: registry.jclee.me
      # No credentials needed for public registry