apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  # Registry configuration for registry.jclee.me
  registries.conf: |
    registries:
    - name: registry.jclee.me
      api_url: https://registry.jclee.me
      prefix: registry.jclee.me
      insecure: no
      default: true
  
  # Log level configuration
  log.level: "debug"
  
  # Git commit configuration
  git.commit-message-template: |
    chore: update image {{.AppName}} to {{.NewTag}}
    
    Image updated by ArgoCD Image Updater
    Previous: {{.OldTag}}
    New: {{.NewTag}}
  
  # Kustomize configuration
  kustomize.build-options: |
    --enable-helm
    --load-restrictor=LoadRestrictionsNone