apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - application.yaml
  - image-updater-configmap.yaml
  - argocd-image-updater-secret.yaml

# ArgoCD 및 Image Updater 설정을 위한 패치
patches:
  - target:
      kind: Application
      name: safework
    patch: |-
      - op: add
        path: /metadata/annotations/argocd-image-updater.argoproj.io~1force-update
        value: "true"