apiVersion: v1
kind: Secret
metadata:
  name: safework-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/JCLEE94/safework.git
  username: JCLEE94
  password: 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
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  name: registry-jclee-me
  url: registry.jclee.me
  username: qws9411
  password: bingogo1