apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
  annotations:
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: "safework=registry.jclee.me/safework"
    argocd-image-updater.argoproj.io/safework.update-strategy: "latest"
    argocd-image-updater.argoproj.io/safework.allow-tags: "regexp:^prod-[0-9]{8}-[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/write-back-method: "git"
    argocd-image-updater.argoproj.io/git-branch: "main"
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    chart: safework
    targetRevision: "*"
    helm:
      values: |
        image:
          repository: registry.jclee.me/safework
          tag: "latest"
          pullPolicy: Always
        imagePullSecrets:
          - name: harbor-registry
        service:
          type: NodePort
          port: 3001
          targetPort: 3001
          nodePort: 32301
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  revisionHistoryLimit: 10