apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: safework
  namespace: argocd
  annotations:
    # ArgoCD Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: "safework=registry.jclee.me/safework"
    argocd-image-updater.argoproj.io/safework.update-strategy: "latest"
    argocd-image-updater.argoproj.io/safework.allow-tags: "regexp:^prod-[0-9]{8}-[a-f0-9]{7}$"
    argocd-image-updater.argoproj.io/write-back-method: "git"
    argocd-image-updater.argoproj.io/git-branch: "main"
spec:
  project: default
  source:
    repoURL: https://charts.jclee.me
    chart: safework
    targetRevision: "*"
    helm:
      values: |
        image:
          repository: registry.jclee.me/safework
          tag: "latest"
          pullPolicy: Always
        imagePullSecrets:
          - name: harbor-registry
        env:
          ADMIN_USERNAME: "admin"
          ADMIN_PASSWORD: "bingogo1"
          DATABASE_URL: "postgresql://admin:password@postgres:5432/health_management"
          REDIS_HOST: "redis"
          REDIS_PORT: "6379"
          JWT_SECRET: "prod-jwt-secret-key"
          ENVIRONMENT: "production"
          TZ: "Asia/Seoul"
  destination:
    server: https://kubernetes.default.svc
    namespace: safework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  revisionHistoryLimit: 10