apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safework

resources:
  # 기본 SafeWork 리소스
  - ../safework/
  
  # Cloudflare Tunnel 리소스
  - ../cloudflare/tunnel-secret.yaml
  - ../cloudflare/cloudflared-deployment.yaml
  - ../cloudflare/tunnel-config.yaml

# Service를 ClusterIP로 패치
patches:
  - target:
      kind: Service
      name: safework
      namespace: safework
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: safework
        namespace: safework
      spec:
        type: ClusterIP
        ports:
        - port: 3001
          targetPort: 3001
          protocol: TCP
          name: http