---
apiVersion: v1
kind: Namespace
metadata:
  name: safework
  labels:
    app: safework
    environment: production
    team: health-management
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: safework-quota
  namespace: safework
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: safework-limits
  namespace: safework
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container