apiVersion: v1
kind: ConfigMap
metadata:
  name: safework-config
  labels:
    app: safework
data:
  # Application Settings
  APP_NAME: "SafeWork Pro"
  APP_VERSION: "1.0.0"
  
  # Server Configuration
  SERVER_PORT: "3001"
  API_PREFIX: "/api/v1"
  
  # Frontend Configuration
  VITE_API_URL: "http://localhost:3001/api/v1"
  
  # Logging
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Performance
  WORKERS: "1"
  WORKER_CONNECTIONS: "1000"
  
  # Health Check
  HEALTH_CHECK_INTERVAL: "30s"
  
  # Korean Locale Settings
  TZ: "Asia/Seoul"
  LANG: "ko_KR.UTF-8"
  LC_ALL: "ko_KR.UTF-8"