apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safework

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: registry.jclee.me/safework
    newTag: latest

commonLabels:
  app: safework
  version: v1.0.0

configMapGenerator:
  - name: safework-env
    literals:
      - ENVIRONMENT=production