apiVersion: v1
kind: Service
metadata:
  name: safework
  labels:
    app: safework
spec:
  type: NodePort
  selector:
    app: safework
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 32301
    protocol: TCP
    name: http