apiVersion: apps/v1
kind: Deployment
metadata:
  name: safework
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: safework
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          initialDelaySeconds: 45
          periodSeconds: 20
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10