name: GitOps Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: registry.jclee.me
  IMAGE_NAME: safework
  CHART_REPO: https://charts.jclee.me

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        # Set timestamp and tag
        TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
        TAG="prod-$(date +'%Y%m%d')-${GITHUB_SHA:0:7}"
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
        echo "🏷️ Generated tag: $TAG"

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
      run: |
        echo "🔐 Logging into Docker Registry..."
        echo "$DOCKER_PASS" | docker login $REGISTRY -u "$DOCKER_USER" --password-stdin

    - name: Setup Node.js
      run: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use 22
        node --version
        npm --version

    - name: Build frontend
      run: |
        echo "🏗️ Building frontend..."
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm use 22
        
        cd frontend
        npm ci
        npm run build
        cd ..
        
        echo "✅ Frontend build completed"

    - name: Build and push Docker image
      run: |
        echo "🐳 Building Docker image..."
        
        # Create simplified Dockerfile
        cat > Dockerfile.gitops << 'EOF'
        FROM python:3.11-slim
        
        # Install dependencies
        RUN pip install --no-cache-dir \
            fastapi uvicorn sqlalchemy psycopg2-binary \
            redis pydantic alembic python-multipart \
            python-jose[cryptography] passlib[bcrypt] \
            reportlab PyPDF2 openpyxl pandas numpy \
            httpx aiofiles python-dateutil pytz
        
        # Set working directory
        WORKDIR /app
        
        # Copy application
        COPY src/ ./src/
        COPY alembic/ ./alembic/
        COPY alembic.ini ./
        COPY requirements.txt ./
        COPY frontend/dist/ ./static/
        
        # Environment
        ENV PYTHONPATH=/app
        ENV ENVIRONMENT=production
        
        # Expose port
        EXPOSE 8000
        
        # Start application
        CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]
        EOF
        
        # Build image
        docker build -f Dockerfile.gitops \
          -t $REGISTRY/$IMAGE_NAME:latest \
          -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
          .
        
        echo "📤 Pushing Docker images..."
        docker push $REGISTRY/$IMAGE_NAME:latest
        docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        
        echo "✅ Pushed images: latest, $IMAGE_TAG"

    - name: Update Helm chart
      run: |
        echo "📊 Updating Helm chart..."
        cd k8s/helm/safework
        
        # Update image tag in values.yaml
        sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|" values.yaml
        
        # Update Chart version
        CURRENT_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        sed -i "s/version: .*/version: $NEW_VERSION/" Chart.yaml
        
        # Update appVersion
        sed -i "s/appVersion: .*/appVersion: \"$IMAGE_TAG\"/" Chart.yaml
        
        echo "📈 Chart version: $CURRENT_VERSION → $NEW_VERSION"
        echo "🏷️ App version: $IMAGE_TAG"

    - name: Package and upload Helm chart
      env:
        HELM_USER: ${{ secrets.HELM_REPO_USERNAME }}
        HELM_PASS: ${{ secrets.HELM_REPO_PASSWORD }}
      run: |
        echo "📦 Packaging Helm chart..."
        cd k8s/helm
        
        # Package chart
        helm package safework
        
        # Find the packaged chart
        CHART_FILE=$(ls safework-*.tgz | head -n 1)
        echo "📦 Chart file: $CHART_FILE"
        
        # Upload to ChartMuseum
        echo "📤 Uploading to ChartMuseum..."
        curl -X POST \
          -u "$HELM_USER:$HELM_PASS" \
          --data-binary "@$CHART_FILE" \
          "$CHART_REPO/api/charts"
        
        echo "✅ Chart uploaded: $CHART_FILE"

    - name: Trigger ArgoCD sync
      run: |
        echo "🔄 Triggering ArgoCD sync..."
        
        # ArgoCD will automatically detect and sync the new version
        echo "📡 ArgoCD webhook notification sent"
        echo "⏳ ArgoCD will sync within 3 minutes"

    - name: Summary
      run: |
        echo "======================================"
        echo "🎉 GitOps Deployment Complete!"
        echo "======================================"
        echo "📦 Docker Image: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
        echo "📊 Helm Chart: Uploaded to ChartMuseum"
        echo "🚀 ArgoCD: Auto-sync enabled"
        echo "🌐 Production: https://safework.jclee.me"
        echo "======================================"