name: Build and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: registry.jclee.me
  IMAGE_NAME: health

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # - name: Login to Private Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            qws941/health:latest
            qws941/health:${{ github.sha }}
          cache-from: type=registry,ref=qws941/health:buildcache
          cache-to: type=registry,ref=qws941/health:buildcache,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 1111
          timeout: 60s
          command_timeout: 30s
        script: |
            # Pull new image
            /usr/local/bin/docker pull qws941/health:latest
            
            # Update compose file to use new image
            cd /volume1/app/health
            /usr/local/bin/docker-compose -f compose.yaml pull health-app
            
            # Deploy with zero downtime
            /usr/local/bin/docker-compose -f compose.yaml up -d health-app
            
            # Wait for health check
            sleep 15
            
            # Verify deployment
            curl -f http://localhost:3001/health || echo "Health check failed but continuing"