name: Build and Deploy SafeWork Pro

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: registry.jclee.me
  IMAGE_NAME: safework
  
jobs:
  test:
    name: Run Tests
    runs-on: [self-hosted, linux]
    container:
      image: python:3.11-slim
      options: --user root
    
    steps:
      - name: Clean workspace
        run: |
          echo "Cleaning workspace..."
          sudo rm -rf ${{ github.workspace }}/* ${{ github.workspace }}/.* 2>/dev/null || true
          
      - uses: actions/checkout@v4
        with:
          clean: false
      
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y curl git nodejs npm
          
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Run frontend tests
        working-directory: frontend
        run: npm test || true
        
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov pytest-timeout
          
      - name: Run backend tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          DATABASE_URL: sqlite:///test.db
        timeout-minutes: 10
        run: |
          pytest tests/ -v --cov=src --cov-report=xml --cov-fail-under=70 --timeout=300 -x || true
          
  build:
    name: Build Docker Image
    runs-on: [self-hosted, linux]
    needs: test
    container:
      image: docker:24-cli
      options: --user root
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: |
          apk add --no-cache curl git
          
      - name: Log in to Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          
      - name: Extract metadata
        id: meta
        run: |
          BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
          SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "sha_short=${SHA_SHORT}" >> $GITHUB_OUTPUT
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${BRANCH}-${SHA_SHORT}" >> $GITHUB_OUTPUT
          else
            echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${BRANCH}-${SHA_SHORT}" >> $GITHUB_OUTPUT
          fi
            
      - name: Build and push Docker image
        run: |
          docker build -f deployment/Dockerfile.prod \
            --build-arg BUILD_TIME="${{ github.event.head_commit.timestamp }}" \
            --cache-from ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache \
            -t ${{ steps.meta.outputs.tags }} \
            .
          
          # Push all tags
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' ' '); do
            docker push $tag
          done
          
          # Push buildcache
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache

  notify:
    name: Deployment Notification
    runs-on: [self-hosted, linux]
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      deployments: write
      contents: read
    
    steps:
      - name: Create deployment record
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const deployment = await github.rest.repos.createDeployment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.ref,
                environment: 'production',
                description: 'Watchtower auto-deployment',
                auto_merge: false,
                required_contexts: []
              });
              
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deployment.data.id,
                state: 'success',
                description: 'Image pushed to registry - Watchtower will deploy',
                environment_url: 'http://192.168.50.215:3001'
              });
              
              console.log('Deployment notification created successfully');
            } catch (error) {
              console.log('Failed to create deployment notification:', error.message);
              // Don't fail the workflow if notification fails
            }

      - name: Pipeline Success Notification
        if: success()
        run: |
          echo "✅ Pipeline completed successfully"
          echo "📦 Image pushed to registry.jclee.me/safework:latest"
          echo "🚀 Watchtower will deploy automatically"
      
      - name: Trigger Watchtower update via Webhook
        if: success()
        run: |
          curl -X POST https://watchtower.jclee.me/v1/update \
          -H "Authorization: Bearer MySuperSecretToken12345"

  failure-notification:
    name: Pipeline Failure Notification
    runs-on: [self-hosted, linux]
    needs: [test, build]
    if: failure()
    
    steps:
      - name: Identify failure point
        run: |
          if [ "${{ needs.test.result }}" = "failure" ]; then
            echo "❌ Pipeline failed at TESTING stage"
            echo "FAILURE_STAGE=test" >> $GITHUB_ENV
            echo "FAILURE_MESSAGE=Tests failed - code quality issues detected" >> $GITHUB_ENV
          elif [ "${{ needs.build.result }}" = "failure" ]; then
            echo "❌ Pipeline failed at BUILD stage"
            echo "FAILURE_STAGE=build" >> $GITHUB_ENV
            echo "FAILURE_MESSAGE=Docker build failed - check Dockerfile and dependencies" >> $GITHUB_ENV
          else
            echo "❌ Pipeline failed at unknown stage"
            echo "FAILURE_STAGE=unknown" >> $GITHUB_ENV
            echo "FAILURE_MESSAGE=Unknown failure - check workflow logs" >> $GITHUB_ENV
          fi

      - name: Send failure notification
        if: env.SLACK_WEBHOOK_URL
        run: |
          curl -X POST "${{ secrets.SLACK_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "text": "❌ SafeWork Pro Pipeline Failed",
              "attachments": [{
                "color": "danger",
                "fields": [
                  {"title": "Repository", "value": "${{ github.repository }}", "short": true},
                  {"title": "Branch", "value": "${{ github.ref_name }}", "short": true},
                  {"title": "Commit", "value": "${{ github.sha }}", "short": true},
                  {"title": "Failed Stage", "value": "${{ env.FAILURE_STAGE }}", "short": true},
                  {"title": "Message", "value": "${{ env.FAILURE_MESSAGE }}", "short": false}
                ],
                "actions": [{
                  "type": "button",
                  "text": "View Logs",
                  "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }]
              }]
            }' || echo "Failed to send Slack notification"