name: Claude Max PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  claude-pr-review:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))
    runs-on: [self-hosted, linux]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Claude Max Pull Request Review
        uses: grll/claude-code-base-action@beta
        continue-on-error: true
        with:
          prompt: |
            🔍 **SafeWork Pro Pull Request 전문 검토**
            
            ## 📋 검토 대상 PR 정보:
            - **제목**: ${{ github.event.pull_request.title }}
            - **작성자**: ${{ github.event.pull_request.user.login }}
            - **브랜치**: ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}
            
            ## 🎯 프로젝트 컨텍스트:
            - **시스템**: 건설업 산업안전보건 관리 플랫폼
            - **스택**: FastAPI + React + PostgreSQL + Redis + Kubernetes
            - **규정**: 한국 산업안전보건법, 개인정보보호법 준수
            - **민감데이터**: 근로자 건강정보, 의료기록, 화학물질 정보
            
            ## 🔍 상세 검토 기준:
            
            ### 1. 🛡️ 보안 검토 (Critical)
            - SQL Injection, XSS, CSRF 취약점 분석
            - JWT 토큰 및 세션 관리 보안성
            - 근로자 개인정보 접근 제어 및 암호화
            - API 엔드포인트 인증/인가 체계
            - 민감정보 로깅 및 노출 방지
            - 파일 업로드 보안 (MSDS, 의료기록)
            
            ### 2. 📊 성능 및 확장성
            - 데이터베이스 쿼리 최적화
            - Redis 캐싱 전략 효율성
            - API 응답시간 및 처리량
            - N+1 쿼리 문제 식별
            - 대용량 데이터 처리 최적화
            
            ### 3. 🏗️ 아키텍처 및 코드 품질
            - FastAPI 라우터 구조 및 의존성 주입
            - React 컴포넌트 재사용성 및 상태관리
            - TypeScript 타입 안전성
            - 에러 핸들링 및 예외 처리
            - 테스트 커버리지 및 품질
            
            ### 4. 🦺 도메인 특화 검토
            - 건강검진 데이터 무결성 및 정확성
            - MSDS 화학물질 분류 및 관리 규정 준수
            - 사고보고 프로세스 및 법적 요구사항
            - 산업안전보건법 교육 관리 기능
            - 작업환경 측정 데이터 검증
            
            ### 5. 🌐 사용자 경험 및 접근성
            - 한국어 UI/UX 최적화
            - 모바일 반응형 디자인
            - 접근성 표준 준수
            - 사용자 워크플로우 개선
            
            ## 📋 검토 결과 구조:
            
            ### ✅ **우수한 구현 사항**
            - 잘 설계된 부분들과 그 이유
            - 보안/성능/품질 측면의 장점
            
            ### ⚠️ **개선 필요 사항**
            - **🔴 Critical**: 즉시 수정 필요한 보안/기능 이슈
            - **🟠 High**: 우선적으로 개선해야 할 사항
            - **🟡 Medium**: 다음 스프린트에서 고려할 사항
            - **🟢 Low**: 장기적 개선 아이디어
            
            ### 🚀 **추가 제안사항**
            - 성능 최적화 아이디어
            - 보안 강화 방안
            - 사용자 경험 개선
            - 코드 구조 리팩토링
            
            ### 🧪 **테스트 추천사항**
            - 필요한 단위 테스트
            - 통합 테스트 시나리오
            - 보안 테스트 케이스
            
            **변경된 파일들을 중심으로 상세히 분석하되, 전체 시스템과의 일관성도 검토해주세요.**
            **한국어로 구체적이고 실행가능한 피드백을 제공해주세요.**
            **중요도에 따라 우선순위를 명시해주세요.**
          
          use_oauth: "true"
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          model: "claude-3-sonnet-20240229"
          allowed_tools: "mcp__github__add_issue_comment,mcp__github__create_pull_request_review,mcp__github__get_pull_request_files"