name: Claude Code OAuth Setup

on:
  workflow_dispatch:
    inputs:
      force_login:
        description: 'Force new OAuth login'
        required: false
        type: boolean
        default: false

jobs:
  claude-oauth-setup:
    name: Claude Code OAuth Authentication
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Claude Code OAuth Login
        uses: grll/claude-code-login@v1
        with:
          force: ${{ inputs.force_login }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verify OAuth Token
        run: |
          if [ -f ~/.claude/oauth_token ]; then
            echo "✅ Claude Code OAuth 토큰 설정 완료"
            echo "🔐 토큰 파일 생성됨: ~/.claude/oauth_token"
          else
            echo "❌ OAuth 토큰 설정 실패"
            exit 1
          fi
      
      - name: Test Claude Code Connection
        run: |
          echo "🧪 Claude Code 연결 테스트..."
          # Test basic claude command if available
          if command -v claude &> /dev/null; then
            claude --version || echo "Claude 명령어는 사용 가능하지만 버전 확인 실패"
          else
            echo "ℹ️ Claude 명령어를 찾을 수 없음 (정상적인 상황)"
          fi
          echo "✅ OAuth 설정 프로세스 완료"