name: SafeWork Pro - GitHub Container Registry CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=prod-{{date 'YYYY.MM.DD'}}-{{sha}}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/Dockerfile.prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_TIME=${{ steps.meta.outputs.created }}
      
      - name: Update K8s manifests
        run: |
          # Get the new image tag
          NEW_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod-$(date +%Y.%m.%d)-${GITHUB_SHA::7}"
          
          # Update kustomization.yaml
          sed -i "s|newTag:.*|newTag: prod-$(date +%Y.%m.%d)-${GITHUB_SHA::7}|g" k8s/safework/kustomization.yaml
          sed -i "s|name:.*safework.*|name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}|g" k8s/safework/kustomization.yaml
          
          # Commit changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s/safework/kustomization.yaml
          git commit -m "chore: update image to ${NEW_IMAGE} [skip ci]"
          git push