name: Pipeline Health Monitor

on:
  schedule:
    - cron: '0 */6 * * *'  # 6시간마다 실행
  workflow_dispatch:

jobs:
  monitor:
    name: Monitor CI/CD Health
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check recent workflow runs
        id: check-runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get recent workflow runs
          RUNS=$(gh run list --limit 10 --json status,conclusion,name,createdAt)
          
          # Count failures
          FAILED=$(echo "$RUNS" | jq '[.[] | select(.conclusion == "failure")] | length')
          TOTAL=$(echo "$RUNS" | jq 'length')
          
          # Calculate failure rate
          if [ $TOTAL -gt 0 ]; then
            FAILURE_RATE=$((FAILED * 100 / TOTAL))
          else
            FAILURE_RATE=0
          fi
          
          echo "failure_rate=$FAILURE_RATE" >> $GITHUB_OUTPUT
          echo "failed_count=$FAILED" >> $GITHUB_OUTPUT
          echo "total_count=$TOTAL" >> $GITHUB_OUTPUT
          
          # Print summary
          echo "## CI/CD Health Summary"
          echo "- Total runs: $TOTAL"
          echo "- Failed runs: $FAILED"
          echo "- Failure rate: $FAILURE_RATE%"
          
      - name: Check Docker registry status
        continue-on-error: true
        run: |
          echo "## Registry Status Check"
          
          # Check registry availability
          if curl -s -m 5 https://registry.jclee.me/v2/ > /dev/null; then
            echo "✅ Registry is accessible"
            
            # Check if safework repository exists
            if curl -s -m 5 https://registry.jclee.me/v2/safework/tags/list | grep -q "NAME_UNKNOWN"; then
              echo "⚠️ SafeWork repository not found in registry"
            else
              echo "✅ SafeWork repository exists"
              curl -s -m 5 https://registry.jclee.me/v2/safework/tags/list | jq . || echo "Tags list unavailable"
            fi
          else
            echo "❌ Registry is not accessible"
          fi
          
      - name: Generate health report
        if: steps.check-runs.outputs.failure_rate > 20
        run: |
          cat > pipeline-health-report.md << EOF
          # CI/CD Pipeline Health Report
          
          ## Alert: High Failure Rate Detected
          
          - **Failure Rate**: ${{ steps.check-runs.outputs.failure_rate }}%
          - **Failed Runs**: ${{ steps.check-runs.outputs.failed_count }}/${{ steps.check-runs.outputs.total_count }}
          - **Timestamp**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          ## Common Failure Patterns
          
          1. **413 Request Entity Too Large**
             - Status: Mitigated by using GitHub Container Registry
             - Action: Monitor image size growth
          
          2. **Test Timeouts**
             - Status: Improved with parallel execution
             - Action: Continue monitoring test duration
          
          3. **Service Container Issues**
             - Status: Fixed with increased health check retries
             - Action: Monitor for recurrence
          
          ## Recommendations
          
          1. Review recent failed runs
          2. Check for new error patterns
          3. Update retry logic if needed
          
          EOF
          
          # Create issue if failure rate is high
          if [ ${{ steps.check-runs.outputs.failure_rate }} -gt 30 ]; then
            gh issue create \
              --title "CI/CD Pipeline Health Alert: ${{ steps.check-runs.outputs.failure_rate }}% Failure Rate" \
              --body-file pipeline-health-report.md \
              --label "ci/cd,urgent"
          fi