name: Quick Deploy to Production

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/test.yml'
      - '.github/workflows/security.yml'

env:
  REGISTRY: registry.jclee.me
  IMAGE_NAME: safework

jobs:
  deploy:
    name: Build and Deploy
    runs-on: [self-hosted, linux]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          
      - name: Build and push Docker image
        run: |
          docker build -f deployment/Dockerfile.prod \
            --build-arg BUILD_TIME="${{ github.event.head_commit.timestamp }}" \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      - name: Trigger Watchtower update
        if: success()
        run: |
          echo "✅ Docker image pushed to registry"
          echo "🚀 Triggering Watchtower update..."
          curl -X POST https://watchtower.jclee.me/v1/update \
            -H "Authorization: Bearer MySuperSecretToken12345" || true
          echo "✅ Deployment triggered"