name: SafeWork Pro - Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday

jobs:
  security-scan:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true
          
  docker-scan:
    runs-on: self-hosted
    needs: security-scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Pull SafeWork Pro Docker image for scan
        run: |
          docker pull registry.jclee.me/safework:latest
          docker tag registry.jclee.me/safework:latest safework-scan:latest
        
      - name: Run Trivy on Docker image
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'safework-scan:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '10m'
        continue-on-error: true
          
  dependency-check:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Python Dependency Check
        run: |
          python -m pip install --upgrade pip
          python -m pip install safety
          mkdir -p $HOME/.safety || true
          safety check --json || echo "Safety check completed with warnings"
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: npm audit
        run: |
          export NPM_CONFIG_CACHE=/tmp/.npm
          mkdir -p /tmp/.npm
          npm install --cache /tmp/.npm
          npm audit --audit-level=high || echo "npm audit completed with warnings"