name: Simple CI/CD

on:
  push:
    branches: [ main ]

env:
  REGISTRY: registry.jclee.me
  IMAGE_NAME: safework

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Push
      run: |
        # Login
        echo "bingogo1" | docker login registry.jclee.me -u admin --password-stdin
        
        # Build
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
        # Push
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
    - name: Update K8s
      run: |
        kubectl set image deployment/safework safework=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -n safework
        kubectl rollout status deployment/safework -n safework