name: SafeWork Pro - Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: [self-hosted, linux]
    container:
      image: python:3.11-slim
      options: --user root
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: health_management
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov pytest-asyncio pytest-timeout
          
      - name: Run tests
        env:
          DATABASE_URL: postgresql://admin:password@postgres:5432/health_management
          REDIS_URL: redis://redis:6379/0
          JWT_SECRET: test-secret-key
          PYTHONPATH: ${{ github.workspace }}
        timeout-minutes: 10
        run: |
          pytest tests/ -v --cov=src --cov-report=html --cov-report=term --timeout=300 -x || true
          
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  test-frontend:
    runs-on: [self-hosted, linux]
    container:
      image: node:18-slim
      options: --user root
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false
        
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Run tests
        working-directory: frontend
        run: npm run test || true
        
      - name: Build frontend
        working-directory: frontend
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/