name: Quick Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  quick-test:
    name: Quick Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
          
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-timeout
      
      - name: Run quick tests
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379/0
          JWT_SECRET: quick-test-secret
          ENVIRONMENT: development
        run: |
          # Run only fast unit tests
          pytest tests/ -v \
            -m "not slow and not integration" \
            --timeout=30 \
            --maxfail=5 \
            -x \
            || echo "Some tests failed, check logs"
      
      - name: Check code quality
        continue-on-error: true
        run: |
          pip install black isort flake8
          black --check src/ tests/ || echo "Code formatting issues found"
          isort --check-only src/ tests/ || echo "Import sorting issues found"
          flake8 src/ tests/ --max-line-length=120 || echo "Linting issues found"