apiVersion: v1
kind: ConfigMap
metadata:
  name: safework-config
  labels:
    app: safework
data:
  # Application configuration
  environment: "development"
  log_level: "info"
  
  # Database configuration (non-sensitive defaults)
  database_host: "localhost"
  database_port: "5432"
  database_name: "health_management"
  database_user: "admin"
  
  # Redis configuration (non-sensitive defaults)
  redis_host: "localhost"
  redis_port: "6379"
  redis_db: "0"
  
  # Application settings
  cors_origins: "*"
  api_prefix: "/api/v1"
  docs_url: "/api/docs"
  redoc_url: "/api/redoc"
  
  # Frontend configuration
  react_app_api_base_url: "/api/v1"
  react_app_ws_url: "ws://localhost:8081"