apiVersion: v1
kind: Service
metadata:
  name: safework
  labels:
    app: safework
    component: backend
spec:
  type: NodePort
  selector:
    app: safework
    component: backend
  ports:
  - name: http
    port: 80
    targetPort: 3001
    nodePort: 30001
    protocol: TCP
  - name: api
    port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP